# Intro to TensorFlow B - TensorFlow 2.0 Course

## Tensor
A tensor is generalization of vectors and matrices to potentially higher dimensions. Internally, TehsorFlow represents tensors as n-dimensional arrays of base datatypes.

In [9]:
import tensorflow as tf

## Creating Tensors

In [10]:
# create some different tensors

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Rank/Degree of Tensors

In [11]:
rank1_tensor = tf.Variable(["test", "ok", "tim"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"], ["ok", "ok"]], tf.string)

In [12]:
tf.rank(string), tf.rank(rank1_tensor), tf.rank(rank2_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

## Shape of Tensors

In [13]:
rank2_tensor.shape

TensorShape([3, 2])

## Changing Shape

In [14]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells the tensor to calculate the size of the dimension in that place

tensor1, tensor2, tensor3

(<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

### Type of Tensors
* Variable
* Constant
* Placeholder
* SparseTensor

## Evaluating Tensors

In [31]:
tf.compat.v1.disable_eager_execution()

with tf.compat.v1.Session() as sess: 
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(tensor1))

0


In [34]:
# tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\zuoch\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


## Practice

In [50]:
t = tf.zeros([5,5,5,5])
print(t)

Tensor("zeros_4:0", shape=(5, 5, 5, 5), dtype=float32)


In [38]:
t = tf.reshape(t, [625])
print(t)

Tensor("Reshape_2:0", shape=(625,), dtype=float32)


In [51]:
t = tf.reshape(t, [125, -1])
print(t)

Tensor("Reshape_3:0", shape=(125, 5), dtype=float32)
